spring:
  data:
    mongodb:
      uri: mongodb+srv://rolemaster-db-user:r0l3mAst3R@cluster0.kgfrk.mongodb.net/rolemaster?retryWrites=true&w=majority
      #uri: mongodb://localhost/rolemaster?retryWrites=true&w=majority

logging:
  level:
    root: WARN
    org.labcabrera: DEBUG
    org.mongodb: INFO
    org.mongodb.driver.protocol.command: INFO
    
springdoc:
  swagger-ui:
    operationsSorter: alpha
