spring:
  profiles:
    active: ${ROLEMASTER_CORE_PROFILE:local}

logging:
  level:
    root: WARN
    org.labcabrera: DEBUG
    org.mongodb: INFO
    org.mongodb.driver.protocol.command: INFO
    
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha

app:
  openapi:
    version: 1.0-beta

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost/rolemaster?retryWrites=true&w=majority
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb+srv://${ROLEMASTER_CORE_DB_USERNAME}:${ROLEMASTER_CORE_DB_PASSWORD}@cluster0.kgfrk.mongodb.net/rolemaster?retryWrites=true&w=majority

    

