spring:
  data:
    mongodb:
      uri: ${ROLEMASTER_CORE_MONGODB_URI:mongodb://localhost/rolemaster?retryWrites=true&w=majority}
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    root: WARN
    org.labcabrera: DEBUG
    org.mongodb: INFO
    org.mongodb.driver.protocol.command: INFO
    
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha

app:
  openapi:
    version: 1.0-beta
