spring:
  data:
    mongodb:
      uri: ${ROLEMASTER_CORE_MONGODB_URI:mongodb://localhost/rolemaster?retryWrites=true&w=majority}
  jackson:
    default-property-inclusion: NON_NULL

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: rolemaster-core
            client-secret: A53z77kJjn0MkGJK7qL2y23HWR9xKkXR
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            authorization-uri: http://localhost:8090/auth/realms/rolemaster/protocol/openid-connect/auth
            token-uri: http://localhost:8090/auth/realms/rolemaster/protocol/openid-connect/token
            user-info-uri: http://localhost:8090/auth/realms/rolemaster/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8090/auth/realms/rolemaster/protocol/openid-connect/certs
            user-name-attribute: preferred_username

logging:
  level:
    root: DEBUG
    org:
      labcabrera: DEBUG
      mongodb: INFO
    sun: INFO
    javax: INFO

springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha

app:
  openapi:
    version: 1.0-beta
